
[Localization]
# 
# Introduced in: 1.0
# Updated in: 2.5
# 
# Set the 'GameLocalization' parameter to one of the following numerical values 
# to change the game language:
# 
#    -1 = Default (based on the system registry)
#     0 = English (US)
#     1 = French
#     2 = German
#     3 = Italian
#     4 = Spanish
#     5 = English (UK)
#     6 = Russian
#     7 = Japanese
# 
# To customize main menu localization, set 'MenuLocalization' to the name of a 
# localization folder in the '../MainMenu/Translations' folder.
# 
GameLocalization=-1
MenuLocalization=English

[Image]
# 
# Introduced in: 1.0
# Updated in: 2.0
# 
# Set the 'ShowImage' parameter to change the title screen image.
# The image must be located in the "../Graphics/Base/" folder.
# 
#    -1 = No image
#     0 = Random image
#     1-6 = Fixed image (select a specific image by number)
# 
ShowImage=0

[FontType]
# 
# Introduced in: 1.0
# Updated in: -
# 
# Set 'Font1' and 'Font2' to any installed font available on the user's system.
#     'Font1' is primarily used across various UI components.
#     'Font2' is exclusively used for options in the Settings menu.
# 
Font1=Georgia
Font2=Century

[Layout]
# 
# Introduced in: 1.0
# Updated in: 2.3
# 
# Adjust the following values if the menu scale appears too small to read.
# 
LayoutTopScale=2.50
LayoutMidScale=1.20
LayoutBotScale=1.00
LayoutSpacing=0.01
	
